- shell:
    -
        command: sudo pacman -S --needed --noconfirm sxiv htop feh keepassxc picom
        description: "Install other command line utils"
        stdin: true
        stdout: true
        stderr: true
