- shell:
    - ["git submodule update --remote --merge --recursive", "Installing submodules"]

- link:
    ~/.config/nvim: config/nvim

- shell:
    - ['nvim --headless +qa && nvim --headless "+Lazy! sync" +qa', "Install plugin manager and update Plugins"]
