- shell:
    - ["git submodule update --remote --merge --recursive config/nvim", "Installing submodules"]

- link:
    ~/.config/nvim: config/nvim

- shell:
    - ['GOPATH=$HOME/.local/share/go nvim --headless +qa && nvim --headless "+Lazy! sync && nvim --headless +MasonToolsInstallSync +MasonToolsUpdateSync +qa', "Install plugin manager, update Plugins and install lsps"]
