- shell:
    - ["git submodule update --remote --merge --recursive", "Installing submodules"]

- link:
    ~/.config/nvim: config/nvim

- shell:
    - ["nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'", "Install/Update Plugins"]
