- shell:
    - ["git submodule update --remote --merge --recursive", "Installing submodules"]

- link:
    ~/.config/nvim: config/nvim

- shell:
    - [nvim -c PackerSync -c PackerCompile -c qall, "Install/Update Plugins"]
