- shell:
    - command: git clone https://github.com/wyne/fasder /tmp/fasder
      description: "Cloning fasder directory to tmp"
    - command: cd /tmp/fasder && go build
      description: "Building fasder binary in repository"
    - command: mkdir -pv $HOME/.local/bin && mv /tmp/fasder/fasder $HOME/.local/bin/
      description: "Move fasder binary to created PATH directory"
    - command: rm -rf /tmp/fasder
      description: "Clean up fasder tmp"
