- shell:
    - command: sudo pacman -S --needed --noconfirm zsh
      description: "Install zsh"
      stdin: true
    - command: "echo $SHELL | grep zsh || chsh -s $(which zsh)"
      description: "Change shell to zsh. Please enter password for user."
      stdin: true
