- link:
    ~/.config/zsh: config/zsh
    ~/.zshenv: config/zsh/zshenv
- shell:
    - command: "zsh -c 'source ~/.config/zsh/.zshrc && zsh'"
      description: "Run zsh to install antidote with plugins"
      stderr: true
      quiet: true
