- shell:
    -
        command: sudo pacman -S --needed --noconfirm starship diskonaut ripgrep htop nnn task udevil ipython lazygit
        description: "Install other command line utils"
        stdin: true
        stdout: true
        stderr: true
