- shell:
    -
        command: sudo pacman -S --needed --noconfirm neovim python-pip python-pynvim ctags go nodejs npm go unzip gcc
        description: "Install neovim and dependencies"
        stdin: true
        stdout: true
        stderr: true
