- shell:
    -
        command: sudo pacman -S --needed --noconfirm i3status py3status alsa-utils pamixer
        description: "Install py3status"
        stdin: true
        stdout: true
        stderr: true
