- shell:
   -
    command: sudo pacman -S --needed --noconfirm python python-pip go nodejs npm unzip gcc jq which less make man-pages
    description: "Install base utility tools for further installation and usage"
    stdin: true
    stdout: true
    stderr: true
